name: Paratranz To GitHub

on:
  schedule:
    # 每天北京时间早上9点和晚上9点运行
    - cron: "0 1,13 * * *"
  workflow_dispatch:

jobs:
  paratranz-to-gitHub:
    name: Paratranz To GitHub
    environment: PARATRANZ_ENV
    runs-on: ubuntu-latest
    env:
      API_TOKEN: ${{ secrets.API_KEY }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PROJECT_ID: ${{ vars.ID }}
    outputs:
      changed: ${{ steps.commit.outputs.changed }} # 定义输出变量
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          pip install requests
          pip install nbtlib
      - name: Configure Git
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "VM[BOT]"
      - name: Checkout main branch
        run: git checkout main
      - name: Paratranz To GitHub
        run: python .github/workflows/para2github.py
      - name: Commit changes
        id: commit
        run: |
          if [[ -n $(git status -s) ]]; then
            git add .
            git commit -m '从Paratranz同步翻译'
            git push origin main
            echo "changed=true" >> $GITHUB_OUTPUT # 使用 $GITHUB_OUTPUT 设置输出
            echo "译文变动，发布release！"
          else
            echo "changed=false" >> $GITHUB_OUTPUT # 使用 $GITHUB_OUTPUT 设置输出
            echo "译文不变，取消发布release！"
          fi
  release:
    name: Create Release
    runs-on: ubuntu-latest
    environment: PARATRANZ_ENV
    needs: paratranz-to-gitHub
    if: ${{ needs.paratranz-to-gitHub.outputs.changed == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Upload CNPack folder
        uses: actions/upload-artifact@v4
        with:
          name: CNPack
          path: ./CNPack
      - name: Get current datetime for tag
        id: datetime
        run: echo "datetime=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV
      - name: Zip CNPack folder
        run: zip -r "VM-CNPack-${{ env.datetime }}.zip" ./CNPack
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: "VM-CNPack-${{ env.datetime }}.zip"
          path: "VM-CNPack-${{ env.datetime }}.zip"
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "VM-CNPack-${{ env.datetime }}.zip"
          tag: "VM-CNPack-Release-${{ env.datetime }}"
          name: "VM CNPack Release ${{ env.datetime }}"
          body: "自动生成的最新汉化补丁"
          draft: false
          prerelease: false
